import { useEffect, useMemo, useState } from 'react';
import axios from 'axios';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { Activity, AlertTriangle, BarChart3, Bell, Brain, CheckCircle2, ChevronRight, FileText, Fingerprint, LayoutDashboard, ListFilter, Radar, Search, Settings, Shield, ShieldAlert, UserCog } from 'lucide-react';
import './App.css';

// In local Vite development an empty base uses the proxy configured in
// vite.config.js. Production deployments set VITE_API_BASE to their public API.
const API = import.meta.env.VITE_API_BASE || '';
const navigation = ['Dashboard Overview', 'Live AWS Activity', 'Security Logs', 'Threats', 'Incidents', 'MITRE ATT&CK', 'UEBA', 'Exposure Management', 'Response & Approval', 'IAM Monitoring', 'GuardDuty', 'CloudTrail', 'Security Hub', 'Compliance', 'Email Alerts', 'Reports', 'Settings'];
const serviceTabs = new Set(['IAM Monitoring', 'GuardDuty', 'CloudTrail', 'Security Hub']);
const severityClass = value => String(value || 'low').toLowerCase().replace(' ', '-');
const time = value => value ? new Date(value).toLocaleString('en-IN', { timeZone: 'Asia/Kolkata' }) : '-';

function Stat({ label, value, icon: Icon, tone = '' }) { return <div className={`soc-stat ${tone}`}><Icon size={18}/><span>{label}</span><strong>{value ?? 0}</strong></div> }
function Badge({ children, severity }) { return <span className={`soc-badge ${severityClass(severity)}`}>{children}</span> }

function App() {
  const [active, setActive] = useState('Dashboard Overview');
  const [data, setData] = useState({ stats: {}, logs: [], alerts: [], incidents: [], mitre: [], ueba: [], notifications: [], services: [], securityHub: { findings: [], summary: {} }, cspm: { findings: [], summary: {} }, soar: [], email: { configuration: {}, recent_alerts: [] } });
  const [connected, setConnected] = useState(false);
  const [connectionError, setConnectionError] = useState('');
  const [query, setQuery] = useState('');
  const refresh = async () => {
    try {
      const responses = await Promise.allSettled([
        axios.get(`${API}/api/stats`), axios.get(`${API}/api/logs?limit=200`), axios.get(`${API}/api/alerts?limit=200`), axios.get(`${API}/api/incidents?limit=100`), axios.get(`${API}/api/mitre`), axios.get(`${API}/api/ueba`), axios.get(`${API}/api/notifications?limit=25`), axios.get(`${API}/api/services`), axios.get(`${API}/api/security-hub/findings?page_size=50`), axios.get(`${API}/api/cspm/findings`), axios.get(`${API}/api/soar/actions`), axios.get(`${API}/api/email/status`)
      ]);
      const result = (index, fallback) => responses[index].status === 'fulfilled' ? responses[index].value.data : fallback;
      const stats = result(0, {}), logs = result(1, []);
      setData(current => ({ ...current, stats, logs, alerts: result(2, current.alerts), incidents: result(3, current.incidents), mitre: result(4, current.mitre), ueba: result(5, current.ueba), notifications: result(6, current.notifications), services: result(7, current.services), securityHub: result(8, current.securityHub), cspm: result(9, current.cspm), soar: result(10, current.soar), email: result(11, current.email) }));
      const coreOnline = responses[0].status === 'fulfilled' && responses[1].status === 'fulfilled';
      setConnected(coreOnline);
      setConnectionError(coreOnline ? '' : `Cannot reach ${API}/api/${responses[0].status !== 'fulfilled' ? 'stats' : 'logs'}: ${responses.find(item=>item.status==='rejected')?.reason?.message || 'network request failed'}`);
    } catch (error) { setConnected(false); setConnectionError(`Cannot reach ${API}: ${error.message || 'network request failed'}`); }
  };
  useEffect(() => { refresh(); const id = setInterval(refresh, 3000); return () => clearInterval(id); }, []);
  useEffect(() => { if (active !== 'Security Logs') return; const id = setTimeout(async () => { try { const response = await axios.get(`${API}/api/logs/search`, { params: { search: query, page_size: 200 } }); setData(current => ({ ...current, logs: response.data.items })); } catch {} }, 250); return () => clearTimeout(id); }, [query, active]);
  const filteredLogs = useMemo(() => data.logs.filter(log => !query || JSON.stringify(log).toLowerCase().includes(query.toLowerCase())), [data.logs, query]);
  const severity = key => data.incidents.filter(item => item.severity === key && !['Closed', 'False Positive'].includes(item.status)).length;
  const topThreats = [...data.alerts].sort((a,b) => ({Critical:4,High:3,Medium:2,Low:1}[b.severity]||0)-({Critical:4,High:3,Medium:2,Low:1}[a.severity]||0)).slice(0,6);
  const download = async format => { const response = await axios.get(`${API}/api/reports/summary`); const report = response.data; if (format === 'pdf') { const doc = new jsPDF({ orientation: 'landscape' }); doc.setFontSize(18); doc.text('CloudSentinel Enterprise SOC Report', 14, 16); doc.setFontSize(10); doc.text(`Generated: ${time(report.generated_at)}`, 14, 23); const stats = report.executive_summary; doc.text(`Meaningful Events: ${stats.total_logs}   Alerts: ${stats.total_alerts}   Open Incidents: ${stats.open_incidents}`, 14, 30); autoTable(doc, { startY: 38, head: [['Incident', 'Severity', 'Status', 'Risk', 'Actor', 'Threats']], body: report.incidents.map(i => [i.incident_id, i.severity, i.status, i.risk_score, i.actor, i.threats.join(' | ')]), styles: { fontSize: 8 }, headStyles: { fillColor: [13, 71, 90] } }); doc.save('CloudSentinel_SOC_Report.pdf'); return; } const body = format === 'json' ? JSON.stringify(report, null, 2) : ['Incident ID,Severity,Status,Risk Score,Actor,Threats', ...report.incidents.map(i => [i.incident_id,i.severity,i.status,i.risk_score,i.actor,`"${i.threats.join(' | ')}"`].join(','))].join('\n'); const blob = new Blob([body], { type: format === 'json' ? 'application/json' : 'text/csv' }); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href=url; link.download=`CloudSentinel_SOC_Report.${format}`; link.click(); URL.revokeObjectURL(url); };

  const renderOverview = () => <>
    <section className="soc-title"><div><p>Enterprise AWS Security Operations</p><h1>Security posture at a glance</h1></div><button onClick={refresh}>Refresh intelligence</button></section>
    <section className="soc-stats"><Stat icon={Activity} label="Meaningful Events" value={data.stats.total_logs}/><Stat icon={AlertTriangle} label="Security Alerts" value={data.stats.total_alerts} tone="danger"/><Stat icon={ShieldAlert} label="Critical Incidents" value={severity('Critical')} tone="danger"/><Stat icon={Radar} label="High Risk Cases" value={severity('High')} tone="warning"/><Stat icon={Fingerprint} label="Active AWS Users" value={data.ueba.length}/><Stat icon={CheckCircle2} label="Closed Cases" value={data.incidents.filter(i=>i.status==='Closed').length}/></section>
    <section className="soc-grid"><Panel title="Priority investigation queue"><IncidentRows items={data.incidents.slice(0,5)}/></Panel><Panel title="Live SOC notifications"><Notifications items={data.notifications.slice(0,7)}/></Panel><Panel title="MITRE ATT&CK coverage"><MitreRows items={data.mitre.slice(0,7)}/></Panel><Panel title="AWS service activity"><ServiceRows items={data.services.slice(0,7)}/></Panel></section>
  </>;
  const renderActivity = () => <Panel title="Live AWS activity" subtitle="Readable CloudTrail, Security Hub, and GuardDuty activity"><LogTable logs={filteredLogs}/></Panel>;
  const renderLogs = () => <><section className="soc-title"><div><p>Log Explorer</p><h1>Search and investigate security telemetry</h1></div><div className="soc-search"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search user, IP, resource, AWS service or event"/></div></section><LogTable logs={filteredLogs}/></>;
  const renderThreats = () => <Panel title="Active threat detections"><div className="card-grid">{topThreats.map(item=><article className="threat-card" key={item.alert_id}><Badge severity={item.severity}>{item.severity}</Badge><h3>{item.threat_name || item.attack_type}</h3><p>{item.what_happened || item.description}</p><small>{item.event_name} · {item.user_name} · {item.source_ip}</small></article>)}</div></Panel>;
  const renderIncidents = () => <Panel title="Incident management" subtitle="Cases are correlated from related alert evidence"><div className="card-grid">{data.incidents.map(item=><article className="incident-card" key={item.incident_id}><div><Badge severity={item.severity}>{item.severity}</Badge><strong> Risk {item.risk_score}/100</strong></div><h3>{item.threats.join(' · ')}</h3><p><b>Status:</b> {item.status} &nbsp; <b>Analyst:</b> {item.assigned_analyst}</p><p>Actor: {item.actor} · IP: {item.source_ip}</p><p><b>Timeline:</b> {item.attack_path.join(' → ')}</p><p><b>MITRE:</b> {item.mitre_attack.map(x=>x.id).join(', ') || 'Unmapped'}</p><p className="muted">{item.recommended_actions.join(' ')}</p></article>)}</div></Panel>;
  const renderMitre = () => <Panel title="MITRE ATT&CK heatmap" subtitle="Technique detection frequency and related incident evidence"><MitreRows items={data.mitre}/></Panel>;
  const renderUeba = () => <Panel title="User & Entity Behavior Analytics" subtitle="Explainable baselines; no opaque ML-only score"><div className="card-grid">{data.ueba.map(item=><article className="incident-card" key={item.user}><div><Badge severity={item.risk_score>=70?'High':item.risk_score>=45?'Medium':'Low'}>UEBA {item.risk_score}/100</Badge></div><h3>{item.user}</h3><p>{item.event_count} events · Last activity {time(item.last_activity)}</p><p><b>Baseline:</b> {(item.baseline.frequent_services||[]).join(', ') || 'Building baseline'}</p><p>{(item.reasons||[]).join(' • ') || 'No major deviation detected'}</p></article>)}</div></Panel>;
  const renderService = () => <Panel title={active} subtitle="AWS-native findings and service-specific security context"><ServiceRows items={active==='GuardDuty'||active==='Security Hub' ? data.services.filter(x=>x.service.includes(active.toLowerCase())) : data.services}/></Panel>;
  const renderCompliance = () => <Panel title="Compliance & cloud security posture"><div className="card-grid"><article className="incident-card"><h3>CIS AWS Foundations</h3><p>Continuously evidence CloudTrail logging, IAM control changes, public S3 exposure and security-group changes.</p><Badge severity="Medium">Evidence-driven</Badge></article><article className="incident-card"><h3>PCI DSS / SOC 2 / ISO 27001</h3><p>Use incident, IAM, logging and alert evidence for control review and reports.</p><Badge severity="Low">Report ready</Badge></article></div></Panel>;
  const renderSecurityHub = () => !data.securityHub.available ? <Panel title="AWS Security Hub"><p className="empty">{data.securityHub.reason || 'Security Hub returned no findings.'}</p></Panel> : <><section className="soc-stats"><Stat icon={ShieldAlert} label="Findings" value={data.securityHub.summary.total_on_page}/><Stat icon={AlertTriangle} label="Critical" value={data.securityHub.summary.Critical} tone="danger"/><Stat icon={AlertTriangle} label="High" value={data.securityHub.summary.High} tone="warning"/><Stat icon={Activity} label="Active" value={data.securityHub.summary.active}/></section><Panel title="Live Security Hub findings"><div className="table-wrap"><table><thead><tr><th>Severity</th><th>Title</th><th>Account</th><th>Region</th><th>Resource</th><th>Compliance</th><th>Updated</th></tr></thead><tbody>{data.securityHub.findings.map(f=><tr key={f.finding_id}><td><Badge severity={f.severity}>{f.severity}</Badge></td><td><b>{f.title}</b><small>{f.generator}</small></td><td>{f.account_id}</td><td>{f.region}</td><td>{f.resource}</td><td>{f.compliance_status||'-'}</td><td>{time(f.updated_at)}</td></tr>)}</tbody></table></div></Panel></>;
  const renderExposure = () => !data.cspm.scan ? <Panel title="CSPM & Exposure Management" subtitle="Evidence-backed, read-only AWS posture checks"><p className="empty">{data.cspm.reason || 'No CSPM scan has run yet.'} Enable the integration and run the protected scan endpoint; persisted results will appear here.</p></Panel> : <><section className="soc-stats"><Stat icon={ShieldAlert} label="Posture Findings" value={data.cspm.summary.total}/><Stat icon={AlertTriangle} label="Critical" value={data.cspm.summary.Critical} tone="danger"/><Stat icon={AlertTriangle} label="High Exposure" value={data.cspm.summary.High} tone="warning"/><Stat icon={Radar} label="Exposed Resources" value={data.cspm.summary.exposed_resources} tone="danger"/></section><Panel title="CSPM findings" subtitle={`Last scan: ${time(data.cspm.scan.completed_at)} · Account: ${data.cspm.scan.account_id}`}><div className="table-wrap"><table><thead><tr><th>Severity</th><th>Control</th><th>Resource</th><th>Region</th><th>Evidence</th><th>Recommended remediation</th></tr></thead><tbody>{data.cspm.findings.map(f=><tr key={f.finding_id}><td><Badge severity={f.severity}>{f.severity}</Badge></td><td><b>{f.title}</b><small>{f.check_id}</small></td><td>{f.resource}</td><td>{f.region}</td><td>{Object.entries(f.evidence||{}).map(([k,v])=>`${k}: ${Array.isArray(v)?v.join(', '):v}`).join(' · ') || '-'}</td><td>{f.remediation}</td></tr>)}</tbody></table></div>{data.cspm.scan.errors?.length>0&&<p className="empty">{data.cspm.scan.errors.length} AWS checks could not be completed; review the scanner role permissions before treating results as complete.</p>}</Panel></>;
  const renderResponse = () => <Panel title="Response & Approval" subtitle="SOAR actions require a separate approval and remain non-destructive until execution is explicitly enabled."><div className="table-wrap"><table><thead><tr><th>Action</th><th>Incident</th><th>Status</th><th>Requested by</th><th>Approved by</th><th>Requested</th><th>Result</th></tr></thead><tbody>{data.soar.map(a=><tr key={a.action_id}><td><b>{a.action_label}</b><small>{a.action_id}</small></td><td>{a.incident_id||'-'}</td><td><Badge severity={a.status==='Failed'?'High':a.status==='Executed'?'Low':'Medium'}>{a.status}</Badge></td><td>{a.requested_by}</td><td>{a.approved_by||'-'}</td><td>{time(a.requested_at)}</td><td>{a.result?.message||a.result?.error||'Awaiting approval'}</td></tr>)}</tbody></table></div>{data.soar.length===0&&<p className="empty">No response actions are queued. Create approval-gated actions through the protected SOC API.</p>}</Panel>;
  const renderEmail = () => <><section className="soc-stats"><Stat icon={Bell} label="Email Alerts" value={data.email.configuration.enabled?'Enabled':'Disabled'} tone={data.email.configuration.ready?'':'warning'}/><Stat icon={CheckCircle2} label="Ready" value={data.email.configuration.ready?'Yes':'No'} tone={data.email.configuration.ready?'':'danger'}/><Stat icon={Activity} label="Minimum Severity" value={data.email.configuration.min_severity||'-'}/><Stat icon={AlertTriangle} label="Recent Failures" value={data.email.recent_alerts.filter(a=>a.email_status==='failed').length} tone="danger"/></section><Panel title="Email delivery status" subtitle={data.email.configuration.ready?`SMTP configured for ${data.email.configuration.to}`:'Configure SMTP variables in backend/.env and restart the backend.'}><div className="table-wrap"><table><thead><tr><th>Severity</th><th>Alert</th><th>Time</th><th>Email delivery</th><th>Reason</th></tr></thead><tbody>{data.email.recent_alerts.map(a=><tr key={a.alert_id}><td><Badge severity={a.severity}>{a.severity}</Badge></td><td>{a.threat_name}</td><td>{time(a.timestamp)}</td><td><Badge severity={a.email_status==='sent'?'Low':a.email_status==='failed'?'High':'Medium'}>{a.email_status}</Badge></td><td>{a.email_reason||'-'}</td></tr>)}</tbody></table></div></Panel></>;
  const renderReports = () => <Panel title="SOC reports" subtitle="Downloads are generated from current backend incidents, MITRE coverage, UEBA, alerts and telemetry."><div className="report-actions"><button onClick={()=>download('pdf')}>Download PDF</button><button onClick={()=>download('csv')}>Download CSV</button><button onClick={()=>download('json')}>Download JSON</button></div></Panel>;
  const renderGeneric = () => <Panel title={active}><p className="empty">This SOC module shares the live event, incident, MITRE, UEBA, and notification APIs. Configure the corresponding AWS integration to populate it.</p></Panel>;
  const content = active==='Dashboard Overview'?renderOverview():active==='Live AWS Activity'?renderActivity():active==='Security Logs'?renderLogs():active==='Threats'?renderThreats():active==='Incidents'?renderIncidents():active==='MITRE ATT&CK'?renderMitre():active==='UEBA'?renderUeba():active==='Exposure Management'?renderExposure():active==='Response & Approval'?renderResponse():active==='Security Hub'?renderSecurityHub():active==='Email Alerts'?renderEmail():active==='Reports'?renderReports():serviceTabs.has(active)?renderService():active==='Compliance'?renderCompliance():renderGeneric();
  return <main className="soc-shell"><aside className="soc-sidebar"><div className="soc-brand"><Shield/> <span>CloudSentinel<small>ENTERPRISE SOC</small></span></div><nav>{navigation.map(item=><button key={item} onClick={()=>setActive(item)} className={active===item?'active':''}>{item==='Dashboard Overview'?<LayoutDashboard/>:item==='UEBA'?<Brain/>:item==='Settings'?<Settings/>:<ChevronRight/>}{item}</button>)}</nav></aside><section className="soc-main"><header className="soc-header"><div title={connectionError}><span className={`live-dot ${connected?'online':''}`}/>{connected?'LIVE AWS SECURITY FEED':connectionError || `BACKEND OFFLINE (${API})`}</div><div><Bell size={17}/> {data.notifications.length} notifications</div></header>{content}</section></main>;
}
function Panel({ title, subtitle, children }) { return <section className="soc-panel"><div className="panel-title"><h2>{title}</h2>{subtitle&&<p>{subtitle}</p>}</div>{children}</section> }
function LogTable({ logs }) { return <div className="table-wrap"><table><thead><tr><th>Time</th><th>Identity</th><th>Event</th><th>Resource</th><th>Region</th><th>IP</th><th>Status</th><th>Threat</th></tr></thead><tbody>{logs.map(log=><tr key={log.event_id}><td>{time(log.timestamp)}</td><td title={log.user_arn}>{log.user_name||'-'}</td><td><b>{log.event_name}</b><small>{log.event_source}</small></td><td>{log.resource_name}</td><td>{log.region}</td><td>{log.source_ip}</td><td><Badge severity={log.activity_status==='Failed'?'High':'Low'}>{log.activity_status}</Badge></td><td>{log.threat_detected?<Badge severity={log.max_severity}>{(log.threat_types||[]).join(', ')}</Badge>:'-'}</td></tr>)}</tbody></table>{logs.length===0&&<p className="empty">No matching security telemetry.</p>}</div> }
function IncidentRows({items}) { return <div className="compact-list">{items.map(i=><div key={i.incident_id}><Badge severity={i.severity}>{i.severity}</Badge><span>{i.threats.join(', ')}</span><strong>{i.risk_score}/100</strong></div>)}</div> }
function Notifications({items}) { return <div className="compact-list">{items.map(i=><div key={i.id}><Badge severity={i.severity}>{i.severity}</Badge><span>{i.title}</span><small>{time(i.timestamp)}</small></div>)}</div> }
function MitreRows({items}) { return <div className="compact-list">{items.map(i=><div key={i.id}><Badge severity="Medium">{i.id}</Badge><span>{i.name} <small>{i.tactic}</small></span><strong>{i.detection_count}</strong></div>)}</div> }
function ServiceRows({items}) { return <div className="compact-list">{items.map(i=><div key={i.service}><span>{i.service}</span><small>{i.events} events</small><strong>{i.alerts} alerts</strong></div>)}</div> }
export default App;
